name: Frontend CI/CD

on:
  push:
    branches: ['main']

jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        working-directory: /dsview/frontend
        run: git pull origin main

      - name: Rebuild & restart frontend
        working-directory: /dsview/frontend
        run: |
          docker compose build
          docker compose up -d --force-recreate
